### ISSUE TITLE
Improve usage documentation for beginners

### ISSUE THREAD

**Issue by mikulabc** [florensie/hcloud-snapshot-backup#1]
Hi @florensie 

I just came across your script here, I hate all other external backup services, all very complicated and time-consuming, the snapshots is a goldmine people should be using more often to do backups :)

Your script seems very cool and promising, but I am a basic user who has no idea where to start to use this, I would love to create snapshots of my hetzner cloud each week 2 copies and retain 4, how would i set this to run Tuesdays and Thursdays at 3pm?

You guys are all professionals, but think of me as that user that is between Noob and Pro, that simply needs some help with a step-by-step instruction, if you can update the description to include a walkthrough for amateurs like me i would be amazing, I am also thinking of all the other users landing here from Google that were looking for automatic snapshots with hetzner cloud

I would be 1000x grateful :) if you can provide some "how to use" sample explanation for Amateurs

I am using hetzner cloud CX11, i can run commands as root as long as its not too complex.

Have a happy new year!

**Comment by florensie** [comment]
I updated the README with some better instructions and notes. You'll want to look up how to use cron (assuming you're using Linux). Basically you can add a rule like this:
```
0 15 * * TUE,THU /path/to/hcloud-snapshot-backup
``` 
From left to right this reads as: "on minute 0 of the 15th hour of every day of every month on tuesday and thursday execute /path/to/hcloud-snapshot-backup".
